### ISSUE TITLE
Router does not allow Port Forwarding

### ISSUE THREAD

**Issue by Jadonr** [net-angel/netangel-dns#1]
I attempted to setup a few ports on my ASUS router to be able to "port forward". When I turn off OpenVPN, port forwarding works fine. But as soon as I enable OpenVPN with NetAngel, then port forwarding stops working. Is there a way to address that or is it simply because traffic is moving through a VPN, then those functions won't work?

This is critical functionality as I have a port on my network that I need to allow traffic through for offsite backups. Since I've had NetAngel enabled, that port fails to allow any traffic in or out and my backups are not allowed to go out.

Note, the DDNS service on the ASUS router also fails to work since the ports do not forward. I attempted to remotely access the router and as long as the VPN service is enabled, it refuses all incoming connections on anything other than the most common ports (e.g. 21, 80, etc). I used the site 'http://portchecker.co/' to verify.

**Comment by eterry1388** [comment]
This needs to be logged in the netangel-dashboard repo.
